### PR TITLE
add authentication options

### PR DESCRIPTION
**Pull request by mickfeech**
## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] Update README with any necessary configuration snippets

- [x] RuboCop passes

- [x] Existing tests pass 

#### Purpose

Checks fail if SSL is enabled and security is enabled on the API service

### CODE REVIEW

**Comment by sstarcher** [comment]
@mickfeech could you pull the common code out into a lib and squash your commits.

An example would be https://github.com/sensu-plugins/sensu-plugins-aws/blob/master/lib/sensu-plugins-aws/common.rb

**Comment by mickfeech** [comment]
@sstarcher They are really just options being passed from the command line.

**Comment by sstarcher** [comment]
they are also 20 lines of options

**Comment by sstarcher** [comment]
I believe these changes are superseded by @GKTheOne added a pull request.  If I'm incorrect free free to reopen the pull request.

**Pull request closed without merging**
